name: Github-Contribution-Grid-Snake

on:

  schedule:
      # run automatically every 24 hours
      # - cron: "0 */24 * * *"
      # run automatically every week on Monday
      - cron: "0 0 * * 1"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
    - master



jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate-github-contribution-grid-snake
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            contribution-grid-snake/snake.svg
            contribution-grid-snake/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push